version: '3'
services:

  mariadb:
    image: mariadb:${MARIADB_VERSION}
    container_name: ${LAMP_DOCKER_NAME}_mariadb
    volumes:
      - ../mysql:/var/lib/mysql
    ports:
      - "${MARIADB_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MARIADB_DATABASE_PASSWORD}
      - MYSQL_USER=${MARIADB_DATABASE_USER}
      - MYSQL_PASSWORD=${MARIADB_DATABASE_PASSWORD}
      - MYSQL_DATABASE=${MARIADB_DATABASE_NAME}
    restart: always

  nginx:
    image: nginx:${NGINX_VERSION}
    container_name: ${LAMP_DOCKER_NAME}_nginx
    volumes:
      - "../:/usr/share/nginx/html"
      - "../log:/var/log/nginx"
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: dockerfilephp
    container_name: ${LAMP_DOCKER_NAME}_php
    volumes:
      - "../:/usr/share/nginx/html"
      - "./php.ini:/usr/local/etc/php/php.ini"

  smtp:
    container_name: ${LAMP_DOCKER_NAME}_smtp
    image: sj26/mailcatcher
    ports:
      - "${SMTP_HTTP}:1080"
      - "${SMTP_IP}:1025"
