<?php

namespace App\Models;

use \Illuminate\Database\Eloquent\Model as EloquentModel;

class Model extends EloquentModel
{
    /**
     * Indicates if the model should be timestamped with userid.
     *
     * @var bool
     */
    public $usesUsers = false;

    public function update(array $attributes = [], array $options = [])
    {
        if($this->usesUsers) {
            $this->updated_by = auth()->user()->id;
        }

        return parent::update($attributes, $options);
    }

    public function save(array $options = [])
    {
        if($this->usesUsers) {
            $this->created_by = auth()->user()->id;
        }

        return parent::save($options); // TODO: Change the autogenerated stub
    }


}
